import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function HeaderBar() {
  return (
    <>
      <div style={{
        display: 'flex',
        justifyContent: 'flex-end',
        borderBottom: '1px solid #000'
      }}>
        <Navigation />
      </div>
      <div style={{padding: '30px'}}></div>
    </>
  )
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HeaderBar />
        {children}
      </body>
    </html>
  );
}
