import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function HeaderBar() {
  return (
    <>
      <div className="flex w-full border-b">
        <Navigation />
      </div>
    </>
  )
}


//      <div style={{
//        display: 'flex',
//        justifyContent: 'flex-end',
//        borderBottom: '1px solid #000'
 


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="h-screen flex flex-col">
          <HeaderBar />
          {children}
        </div>
      </body>
    </html>
  );
}
